# 분산분석 (ANOVA)

- 분산분석(아노바)은 여러 집단의 평균 차이가 통계쩍으로 유의미한지 검정하는 방법
- 주로 3개 이상의 집단을 비교할 때 사용
- (2개 그립비교라면 t-검정을 사용한다.)

- 일원 분산분석(One-way ANOVA)
    - 단일 요인(독립변수 1개)읫 ㅜ준 간 평균 차이를 검정
- 이원 분산분석(Two-way ANOVA)
    - 두 요인(독립변수 2개)의 수준 간, 그들의 상호작용이 평균에 미치는 영향을 검정

- 아래 단어들은 모두 같은 것이다!!
    - 통계학 --> 독립변수, 요인(factor)
    - 머신러닝 --> 피처(feature), 변수, (입력에 해당 되는 컬럼)

- 왜? t-검정을 여러 번 반복하지 않고 ANOVA를 사용하는가??
    - 독립 표본 t-검정을 집단 쌍마다 여러 번 반복하면 1종 오류(귀무가설이 참인데 잘못해서 기각으로 판단하는 오류)가 누적되어 커지는 문제가 발생
    - 연구 질문이 하나라면 이를 한 번의 통계적 검정으로 실시하는 것이 오류율을 통제하는 데 유리하다.
    - ANOVA는 각 요인의 주 효과(main effect)와 상호작용 효과(interaction effect)를 함께 검정할 수 있는 장점이 있다.

## 일원 분산분석(One-way ANOVA)

- 집단을 나누는 요인이 1개이고, 그 집단의 수가 3개 이상일 때 사용

- 기본 가정
    - 독립성 : 각집단의 관측치는 다른 집단의 관측치와 독립적이다. (설계 단계에서 확보하는 기본 가정)
    - 정규성 : 각 집단의 관측치는 정규분포를 따른다. (stats.shapiro())
    - 등분산성 : 모든 집단의 관측치는 동일한 분산을 가진다. (stats.levene())

- 귀무가설과 대립가설 (일원 분산분석 공통 형태)
    - 귀무가설 : 모든 집단의 평균은 동일하다.
    - 대립가설 : 집단의 평균에는 차이가 있다. (모두 다르다는 뜻이 아니라, 적어도 두 그룹 간에는 차이가 있다.)

In [1]:
import pandas as pd

# A, B, C, D 4개 그룹(예: 4가지 비료/조건)의 측정값을 담은 데이터프레임 생성
# 분산분석의 목적: "A/B/C/D 네 그룹의 평균이 서로 통계적으로 다른가?"를 검정
df = pd.DataFrame({
    'A': [10.5, 11.3, 10.8, 9.6, 11.1, 10.2, 10.9, 11.4, 10.5, 10.3],
    'B': [11.9, 12.4, 12.1, 13.2, 12.5, 11.8, 12.2, 12.9, 12.4, 12.3],
    'C': [11.2, 11.7, 11.6, 10.9, 11.3, 11.1, 10.8, 11.5, 11.4, 11.0],
    'D': [9.8, 9.4, 9.1, 9.5, 9.6, 9.9, 9.2, 9.7, 9.3, 9.4]
})

# 상위 2개 행만 확인 (데이터 구조 파악용)
print(df.head(2))

      A     B     C    D
0  10.5  11.9  11.2  9.8
1  11.3  12.4  11.7  9.4

## 사전 가정 검정 - 분산분석 순서

In [2]:
from scipy import stats

print('=== 정규성 검정 ===')
# shapiro() : 각 그룹이 정규분포를 따르는지 검정(귀무가설: 정규분포를 따른다.)
# p-value가 0.05보다 크면 "정규분포를 따른다"라고 판단 ( 귀무가설 채택)
print(stats.shapiro(df['A']))
print(stats.shapiro(df['B']))
print(stats.shapiro(df['C']))
print(stats.shapiro(df['D']))

=== 정규성 검정 ===
ShapiroResult(statistic=0.9649054066073813, pvalue=0.8400161543468654)
ShapiroResult(statistic=0.9468040874196029, pvalue=0.6308700692815115)
ShapiroResult(statistic=0.9701646110856055, pvalue=0.892367306190296)
ShapiroResult(statistic=0.9752339025839644, pvalue=0.9346854448707653)

In [3]:
print('=== 등분간 검정 ===')
# levene() : 여러 그룹의 분산이 동일한지 검정 (귀무가설 : 분산이 모두 같다.)
# ANOVA는 "그룹 간 분산이 같다"전제를 필요로 하므로 먼저 확인해야 한다.
print(stats.levene(df['A'], df['B'], df['C'], df['D']))

=== 등분간 검정 ===
LeveneResult(statistic=1.9355354288758708, pvalue=0.14127835331346628)

In [4]:
print('=== 일원 분산 분석 ===')
# f_oneway() : 실제 일원 분산분석 수행
# 귀무가설(H0) : 네 그룹(A, B, C, D)의 평균이 모두 같다.
# 대립가설(H1) : 적어도 한 그룹의 평균은 다르다.
# 결과 :   F-통계량, p-value 반환 --> p-value < 0.05 --> 귀무가설 기각(그룹 간 차이가 있다.)
print(stats.levene(df['A'], df['B'], df['C'], df['D']))

=== 일원 분산 분석 ===
LeveneResult(statistic=1.9355354288758708, pvalue=0.14127835331346628)

## fromula(수식) 작성 문법 정리

### ~(물결)
- 종속변수(타겟, 정답)와 독립변수(피처, 입력)를 구분
- target ~ a
    - target : 종속변수
    - a : 독립변수

### +(더하기)
- 여러 독립변수를 모델에 포함
- target ~ a + b + c
    - target : 종속변수
    - a, b, c : 여러 독립 변수들

### C(변수)
- 해당 변수를 범주형(Categorical)으로 명시
- 변수가 이미 문자열이면 자동 인식되지만, 숫자로 코딩된 범주형 변수는 반드시 C()로 감싸야 연속형으로 잘못처리되지 않는다.
- 컬럼명에 띄어쓰기나 특수문자가 있으면 formula문법에서 에러가 난다.
    - 먼저 df.rename(columns={'원래컬럼명':'새 컬럼명'}) 컬럼명을 수정한 뒤 모델을 만들어야 한다.

In [6]:
df = pd.read_csv('fertilizer.csv')
df.head()

  비료    성장
0  A  10.5
1  A  11.3
2  A  10.8
3  A   9.6
4  A  11.1

### anova_lm() 출력 표 읽기
- df(자유도, degree of freedom) : 그룹 수 - 1(요인의 자유도)
                                전체 관측치 수 - 그룹 수(잔차의 자유도)
- sum_sq(제곱합, SS) : 그룹별 또는 잔차의 제곱합(sum of squares)
- mean_sq(평균제곱, MS) : sum_sq를 df로 나눈 값
- F(F-통계량) : 그룹 간 분산 / 그룹 내 분산의 비율
- PR(>F)(p-value) : F-통계량에 대한 유의확률

In [7]:
from statsmodels.formula.api import ols
from statsmodels.stats.anova import anova_lm

model = ols('성장 ~C(비료)', df).fit()
print(anova_lm(model))

            df    sum_sq    mean_sq          F        PR(>F)
C(비료)      3.0  43.21875  14.406250  89.126139  1.001838e-16
Residual  36.0   5.81900   0.161639        NaN           NaN

## 이원 분산 분석(Two-way ANOVA)
- 독립변수가 2개 (예: 나무 종류, 비료 종류)일 때 각각의 영향과, 두 변수의 조합(상호작용) 효과까지 분석
- 기본 가정은 일원 분산분석과 동일하게 독립성, 정규성(Shapiro-Wilk), 등분산성(Levene)으로 한다.

- 주효과 2개 + 상호작용 효과 1개 --> 총 3가지 가설을 동시에 검정
    1. 주효과 - 요인 A (예: 학습 방법)
        - 귀무가설 : 학습 방법에 따라 성적 차이가 없다.
        - 대립가설 : 학습 방법에 따라 성적 차이가 있다.
    2. 주효과 - 요인 B (예: 학습장소)
        - 귀무가설 : 학습 장소에 따라 성적 차이가 없다.
        - 대립가설 : 학습 장소에 따라 성적 차이가 있다.
    3. 상호작용 효과
        - 귀무가설 : A요인과 B요인 간에 상호작용이 없다.
        - 대립가설 : A요인과 B요인 간에 상호작용이 있다.

- statmodels의 ols와 anova_ml을 사용한다.

In [ ]:
df = pd.read_csv('tree.csv')

df.sample(10)   # 무작위로 10개

    나무  비료        성장률
62   C   1  48.936650
87   C   3  69.287511
38   B   1  41.718140
58   B   3  64.312634
6    A   1  65.792128
103  D   2  59.977227
1    A   1  48.617357
73   C   2  78.646437
23   A   3  41.752518
110  D   3  51.812288

In [10]:
import statsmodels.api as sm
from statsmodels.formula.api import ols

# 성장률 ~ 나무 + 비료 + 나무:비료
model = ols('성장률 ~ 나무 + 비료 + 나무:비료', data=df).fit()
anova_table = sm.stats.anova_lm(model)
anova_table

             df       sum_sq      mean_sq          F        PR(>F)
나무          3.0  4783.353938  1594.451313  18.391274  9.016693e-10
비료          1.0   873.322002   873.322002  10.073374  1.942421e-03
나무:비료       3.0   394.801585   131.600528   1.517952  2.137666e-01
Residual  112.0  9709.960792    86.696078        NaN           NaN

In [18]:
model = ols('성장률 ~ C(나무) + C(비료) + C(나무):C(비료)', data=df).fit()
anova_table = sm.stats.anova_lm(model)
print(anova_table)

                df       sum_sq      mean_sq          F        PR(>F)
C(나무)          3.0  4783.353938  1594.451313  18.855528  6.600012e-10
C(비료)          2.0  1127.924259   563.962129   6.669256  1.857612e-03
C(나무):C(비료)    6.0   717.520672   119.586779   1.414199  2.157357e-01
Residual     108.0  9132.639448    84.561476        NaN           NaN

In [22]:
print(format(6.600012e-10, '.11f'))
print(format(1.857612e-03, '.11f'))
print(format(2.157357e-01, '.11f'))

0.00000000066
0.00185761200
0.21573570000

#### 상호작용 효과를 *로 간단히 표현하기
- '나무 + 비료 + 나무:비료' --> '나무 * 비료'

In [24]:
model = ols('성장률 ~ C(나무) * C(비료)', data=df).fit()
anova_table = sm.stats.anova_lm(model)
anova_table

                df       sum_sq      mean_sq          F        PR(>F)
C(나무)          3.0  4783.353938  1594.451313  18.855528  6.600012e-10
C(비료)          2.0  1127.924259   563.962129   6.669256  1.857612e-03
C(나무):C(비료)    6.0   717.520672   119.586779   1.414199  2.157357e-01
Residual     108.0  9132.639448    84.561476        NaN           NaN

- 나무 종류 --> 성장률에 유의미한 차이가 있다.
- 비료 종류 --> 비료 종류에 따라 성장률에 유의미한 차이가 있다.   p < 0.05
- 나무와 비료 간의 상호작용은 상장률에 유의미한영향을 주지 않는다. p >= 0.05

- 주효과 2개는 유의미, 상호작용은 유의미하지 않은 패턴이 시험에 자주 출제

### 레빈 검정 (Levene)
- center 파라미터에 따라 mean(Levene  검정) 또는 median(Brown-Forsythe 검정)으로 등분산성을 확인할 수 있다.
    - 문제에서 특별히 명시하지 않으면 기본값을 사용한다.

#### anova_lm(model, typ=숫자)
- typ 파라미터로 제곱합 계산 방식을 조정할 수 있다.

- typ = 1 (기본값) --> 문제에서 특별한 계산 방식을 요구하지 않으면 이것을 사용한다. 모델이 단순한 경우(설계가 균형잡힌 경우) typ값을 바꿔도 결과가 유사하게 나오는 경우가 많다.
    - 순차적 제곱합 - 변수를 하나씩 추가하며 순서대로 영향을 계산
- typ = 2
    - 불순차적 제곱합 - 각 변수가 독립적으로 미치는 영향을 계산
- typ = 3
    - 제곱합 - 상호작용까지 고려한 상태에서 각 변수의 효과 계산