### SECTION 01 - 필터링 최솟값 중앙값(p.166)

In [199]:
import pandas as pd
df1 = pd.read_csv("type1_data1.csv")
df1.head()

     id   age city    f1  f2    f3    f4         f5  subscribed   views
0  id01   2.0   서울   NaN   0  gold  ENFJ  91.297791  2024-07-16  6820.0
1  id02   9.0   서울  70.0   1   NaN  ENFJ  60.339826  2024-05-12  2534.0
2  id03  27.0   서울  61.0   1  gold  ISTJ  17.252986  2024-03-16  7312.0
3  id04  75.0   서울   NaN   2   NaN  INFP  52.667078  2024-07-21   493.0
4  id05  24.0   서울  85.0   2   NaN  ISFJ  29.269869  2024-03-07  1338.0

In [200]:
f5nz = df1['f5'] != 0
df1[f5nz].shape

(102, 10)

In [201]:
df1['views'] = df1['views'].fillna(df1['views'].min())
df1['views'].median()

5924.0

### SECTION 02 - 카테고리, 인덱스 문자열 슬라이싱(p.167)

In [202]:
import pandas as pd
df2 = pd.read_csv('type1_data1.csv')

In [203]:
df2 = df2['subscribed'].value_counts()
df2

subscribed
2025-02-17    16
2024-06-21     3
2024-04-03     2
2024-07-29     2
2024-05-28     2
              ..
2024-07-08     1
2024-07-20     1
2024-06-10     1
2024-02-01     1
2024-05-20     1
Name: count, Length: 96, dtype: int64

In [204]:
# index[0]으로 빈도수 많은 날짜 가져오기 -> [-2:0]으로 왼쪽 2자리(일수) 가져고이 -> int 정수 변환
int(df2.index[0][-2:])

17

### SECTION 03 - 파생변수, 정렬, 인덱싱 (p.168)

In [205]:
import pandas as pd
df3 = pd.read_csv('type1_data1.csv')

In [206]:
df3 = df3.dropna()
df3.shape

(70, 10)

In [207]:
df3['new'] = df3['views']/df3['f1']
df3.head()

,id,age,city,f1,f2,f3,f4,f5,subscribed,views,new
2,id03,27.0,서울,61.0,1,gold,ISTJ,17.252986,2024-03-16,7312.0,119.868852
5,id06,22.0,서울,57.0,0,vip,INTP,20.129444,2024-09-12,21550.0,378.070175
7,id08,38.0,서울,101.0,1,silver,INFJ,83.685380,2024-03-06,3260.0,32.277228
9,id10,95.0,서울,74.0,1,gold,ISFP,98.429899,2024-04-03,9992.0,135.027027
10,id100,47.0,경기,53.0,0,vip,ESFP,33.308999,2024-02-21,15535.0,293.113208

In [208]:
# df3['new'].sort_Values(ascending=False) -> new 컬럼 값만 담긴 Series만 남아 age이 결과에 없어짐
df3 = df3.sort_values('new', ascending=False)
df3.head()

,id,age,city,f1,f2,f3,f4,f5,subscribed,views,new
115,id114,22.0,대구,23.0,0,gold,INTP,0.000000,2025-02-17,9747.0,423.782609
83,id83,73.0,경기,50.0,1,vip,ENTP,80.138280,2024-09-26,19139.0,382.780000
5,id06,22.0,서울,57.0,0,vip,INTP,20.129444,2024-09-12,21550.0,378.070175
105,id104,21.0,서울,13.0,0,silver,ESFJ,0.000000,2025-02-17,4556.0,350.461538
106,id105,21.0,경기,24.0,0,gold,ESFJ,0.000000,2025-02-17,7654.0,318.916667

In [209]:
int(df3.iloc[0,1])

22

### SECTION 04 - 값 변경, 정렬, 합계(p.169)

In [210]:
df4 = pd.read_csv('type1_data1.csv')

In [211]:
df4['views'] = df4['views'].fillna(0)

In [212]:
value = df4['views'].nlargest(10).iloc[-1]
value

9877.0

In [213]:
df4.loc[df4['views']>value,'views'] = value
print(int(df4['views'].sum()))

652812

### SECTION 05 - 문자열 슬라이싱, 파생변수, 평균값(p.170)

In [214]:
df5 = pd.read_csv('type1_data1.csv')

In [215]:
df5['new'] = df5['f4'].str[2:4]

In [216]:
cond5 = df5['new'] == 'FJ'
df5 = df5[cond5]
df5

,id,age,city,f1,f2,f3,f4,f5,subscribed,views,new
0,id01,2.0,서울,NaN,0,gold,ENFJ,91.297791,2024-07-16,6820.0,FJ
1,id02,9.0,서울,70.0,1,NaN,ENFJ,60.339826,2024-05-12,2534.0,FJ
4,id05,24.0,서울,85.0,2,NaN,ISFJ,29.269869,2024-03-07,1338.0,FJ
6,id07,36.3,서울,60.0,1,NaN,ISFJ,9.796378,2024-01-11,61.0,FJ
7,id08,38.0,서울,101.0,1,silver,INFJ,83.685380,2024-03-06,3260.0,FJ
8,id09,3.3,서울,35.0,2,NaN,ESFJ,17.252986,2024-03-21,2764.0,FJ
13,id13,15.0,서울,68.0,0,gold,ESFJ,83.685380,2024-12-30,5643.0,FJ
18,id18,41.0,서울,87.0,2,gold,ISFJ,80.138280,2024-03-03,7933.0,FJ
24,id24,80.0,부산,44.0,0,gold,INFJ,73.586397,2024-09-11,5976.0,FJ
31,id31,86.0,부산,77.0,0,gold,ESFJ,73.586397,2024-02-11,8014.0,FJ
32,id32,25.0,부산,64.0,0,vip,ISFJ,13.049921,2024-05-24,17421.0,FJ
33,id33,47.0,부산,94.0,0,silver,ENFJ,17.252986,2024-04-02,3880.0,FJ
39,id39,56.0,부산,50.0,0,NaN,INFJ,33.308999,2024-12-22,NaN,FJ
41,id41,81.0,대구,55.0,0,gold,ENFJ,37.113739,2024-10-04,8640.0,FJ
45,id45,97.0,대구,88.0,0,gold,ENFJ,13.049921,2024-06-21,8317.0,FJ
52,id52,97.0,대구,82.0,1,gold,ISFJ,90.496999,2024-05-20,8518.0,FJ
54,id54,53.0,대구,NaN,1,gold,ENFJ,69.730313,2024-06-21,5872.0,FJ
57,id57,3.0,대구,111.0,0,silver,ISFJ,29.269869,2024-01-12,4421.0,FJ
59,id59,64.0,대구,NaN,1,silver,ESFJ,20.129444,2024-06-23,4994.0,FJ
63,id63,88.0,경기,86.0,1,silver,ISFJ,73.586397,2024-12-01,4053.0,FJ
67,id67,66.0,경기,52.0,1,NaN,ISFJ,73.586397,2024-06-17,1159.0,FJ
73,id73,90.0,경기,NaN,1,NaN,ISFJ,73.586397,2024-08-12,512.0,FJ
81,id81,86.0,경기,50.0,1,NaN,ISFJ,37.113739,2024-09-14,244.0,FJ
85,id85,83.6,경기,55.0,0,gold,INFJ,80.138280,2024-09-24,6719.0,FJ
99,id99,1.0,경기,47.0,0,gold,ESFJ,97.381034,2024-12-02,6090.0,FJ
105,id104,21.0,서울,13.0,0,silver,ESFJ,0.000000,2025-02-17,4556.0,FJ
106,id105,21.0,경기,24.0,0,gold,ESFJ,0.000000,2025-02-17,7654.0,FJ
119,id118,24.0,부산,94.0,1,vip,ESFJ,0.000000,2025-02-17,2356.0,FJ

In [217]:
print(round(df5['f2'].mean(),2))

0.61

In [218]:
# cond = df5['f5'].str.contains('FJ')
# df5 = df5[cond]
# print(round(df['f2'].mean(),2))

### SECTION 06 - 필터링, 분산(p.172)

In [219]:
df6 = pd.read_csv('type1_data1.csv')

In [220]:
# and는 하나의 참/거짓을 요구하기 때문에 여러 값을 가진 Series와는 궁합이 안 맞음
df6 = df6[(df6['f3'] == 'gold') & (df6['f2'] == 2)]
df6

        id   age city    f1  f2    f3    f4         f5  subscribed   views
18    id18  41.0   서울  87.0   2  gold  ISFJ  80.138280  2024-03-03  7933.0
29    id29 -13.5   부산  47.0   2  gold  ENTP  67.886373  2024-08-28  6793.0
42    id42  65.0   대구  48.0   2  gold  ESTP  33.308999  2024-02-09  5999.0
55    id55  75.0   대구  63.0   2  gold  ENTP  13.049921  2024-02-06  6042.0
64    id64  43.0   경기  62.0   2  gold  ESFP  73.586397  2024-02-22  5995.0
68    id68  35.0   경기  45.0   2  gold  ISFP  67.886373  2024-07-29  8599.0
71    id71  35.0   경기  84.0   2  gold  ISFP  52.667078  2024-07-15  8087.0
101   id68  35.0   경기  45.0   2  gold  ISFP  67.886373  2024-07-29  8599.0
112  id111  22.0   부산  65.0   2  gold  ENTP   0.000000  2025-02-17  7894.0
118  id117  23.0   대구  65.0   2  gold  INFP   0.000000  2025-02-17  6543.0

In [221]:
df6 = round(df6['f1'].var(),2)
df6

235.43

### SECTION 07 - 값 변경(연산), 필터링, 절댓값(p.173)

In [222]:
df7 = pd.read_csv('type1_data1.csv')

In [223]:
df7['age'] = df7['age'] + 1
df7

        id   age city    f1  f2      f3    f4         f5  subscribed   views
0     id01   3.0   서울   NaN   0    gold  ENFJ  91.297791  2024-07-16  6820.0
1     id02  10.0   서울  70.0   1     NaN  ENFJ  60.339826  2024-05-12  2534.0
2     id03  28.0   서울  61.0   1    gold  ISTJ  17.252986  2024-03-16  7312.0
3     id04  76.0   서울   NaN   2     NaN  INFP  52.667078  2024-07-21   493.0
4     id05  25.0   서울  85.0   2     NaN  ISFJ  29.269869  2024-03-07  1338.0
..     ...   ...  ...   ...  ..     ...   ...        ...         ...     ...
115  id114  23.0   대구  23.0   0    gold  INTP   0.000000  2025-02-17  9747.0
116  id115  24.0   부산  65.0   0     vip  ENTP   0.000000  2025-02-17  5628.0
117  id116  24.0   서울  12.0   1  silver  INFP   0.000000  2025-02-17  1267.0
118  id117  24.0   대구  65.0   2    gold  INFP   0.000000  2025-02-17  6543.0
119  id118  25.0   부산  94.0   1     vip  ESFJ   0.000000  2025-02-17  2356.0

[120 rows x 10 columns]

In [224]:
cond7 = (df7['age'] >= 20) & (df7['age'] < 30)
cond7_1 = (df7['age'] >= 30) & (df7['age'] < 40)
result1 = round(abs((df7[cond7]['views'].mean()) - (df7[cond7_1]['views'].mean())),2)
result1

263.13

###  SECTION 08 - 시계열 데이터, 필터링, 데이터 개수(p.174)

In [225]:
df8 = pd.read_csv('type1_data1.csv')

In [226]:
df8['subscribed'] = pd.to_datetime(df8['subscribed'])

In [227]:
result2 = df8[(df8['subscribed'].dt.year == 2024) & (df8['subscribed'].dt.month == 2) & (df8['f3'] == 'gold')]
len(result2)

5

### SECTION 09 - 필터링, 카테고리, 최빈값(p.175)

In [228]:
df9 = pd.read_csv('type1_data1.csv')

In [229]:
df9 = df9[df9['views'] <= 1000]
df9

      id   age city    f1  f2   f3    f4         f5  subscribed  views
3   id04  75.0   서울   NaN   2  NaN  INFP  52.667078  2024-07-21  493.0
6   id07  36.3   서울  60.0   1  NaN  ISFJ   9.796378  2024-01-11   61.0
30  id30  16.0   부산   NaN   0  NaN  ESTJ  17.252986  2024-05-28  240.0
44  id44  44.0   대구   NaN   0  NaN  INTP  16.283854  2024-11-10  546.0
61  id61  87.0   경기  62.0   2  NaN  INTP  69.730313  2024-02-03  218.0
72  id72   8.0   경기  97.0   0  NaN  ESTJ  97.381034  2024-01-30  602.0
73  id73  90.0   경기   NaN   1  NaN  ISFJ  73.586397  2024-08-12  512.0
81  id81  86.0   경기  50.0   1  NaN  ISFJ  37.113739  2024-09-14  244.0
93  id93  21.8   경기  57.0   0  NaN  ISFP  73.586397  2024-06-07   42.0
98  id98  39.0   경기  58.0   2  NaN  INFP  98.429899  2024-10-02  865.0

In [230]:
df9 = df9['f4'].value_counts()
df9.index[0]

'ISFJ'

### SECTION 10 - 그룹핑, 최댓값, 정렬(p.176)

In [231]:
df10 = pd.read_csv('type1_data1.csv')

In [232]:
df10 = df10.dropna()

In [233]:
# 문자형 컬럼이 있어 mean에 오류 -> numeric_only=True코드로 숫자형 컬럼만 계산
df10 = df10.groupby(['city']).mean(numeric_only=True)
df10

            age         f1        f2         f5        views
city
경기    48.704000  61.360000  0.760000  52.106731  8127.880000
대구    49.773333  66.200000  0.666667  27.370166  6819.133333
부산    35.075000  65.875000  0.687500  38.638715  6945.437500
서울    38.000000  60.142857  0.785714  41.122705  7369.142857

In [234]:
result3 = (df10.sort_values('f2', ascending=False).index[0])
result3

'서울'

### SECTION 11 - 슬라이싱, 사분위수, 결측치 제거

In [235]:
df11 = pd.read_csv('type1_data1.csv')

In [236]:
df11 = df11.dropna()

In [237]:
# 70% 지점
end = int(len(df11) * 0.7)
# 70% 데이터 슬라이싱
df11 = df11.iloc[:end]

In [238]:
q3 = df11['views'].quantile(.75)
q1 = df11['views'].quantile(.25)

print(int(q3-q1))

2771

### SECTION 12 - 결측치 처리, 최빈값, 데이터 개수(p.179)

In [239]:
df12 = pd.read_csv('type1_data1.csv')

In [240]:
df12.isnull().sum()

id             0
age            0
city           0
f1            31
f2             0
f3            29
f4             0
f5             0
subscribed     0
views          4
dtype: int64

In [241]:
# subset = 해당 컬럼 결측치 삭제
df12 = df12.dropna(subset=['f1'])

In [242]:
df12['f3'] = df12['f3'].fillna(df12['f3'].mode()[0])

In [243]:
sum(df12['f3'] == 'gold')

63

### SECTION 13 - 결측 데이터 찾기, 필터링, 평균값(p.181)

In [244]:
df13 = pd.read_csv('type1_data1.csv')

In [245]:
df13 = df13[df13['f1'].isnull()]
df13

      id    age city  f1  f2      f3    f4         f5  subscribed    views
0   id01    2.0   서울 NaN   0    gold  ENFJ  91.297791  2024-07-16   6820.0
3   id04   75.0   서울 NaN   2     NaN  INFP  52.667078  2024-07-21    493.0
12  id12   20.0   서울 NaN   0     NaN  ESTP  91.297791  2024-11-30   1367.0
17  id17   74.0   서울 NaN   1    gold  ISTP  67.886373  2024-10-26   9441.0
19  id19   53.0   서울 NaN   0    gold  ISFP  83.685380  2024-12-24   5287.0
21  id21   90.0   부산 NaN   1    gold  ISFP  29.269869  2024-05-03   9690.0
25  id25   34.0   부산 NaN   0    gold  ESTP  60.339826  2024-07-12   8954.0
30  id30   16.0   부산 NaN   0     NaN  ESTJ  17.252986  2024-05-28    240.0
34  id34   65.0   부산 NaN   1  silver  INFP  48.431184  2024-02-01   3163.0
35  id35   30.0   부산 NaN   2  silver  ESTJ  33.308999  2024-06-10   3084.0
37  id37  100.0   부산 NaN   0  silver  ESTP  33.308999  2024-07-08   4068.0
38  id38   87.0   부산 NaN   1     NaN  ESTP  83.685380  2024-06-21   1048.0
44  id44   44.0   대구 NaN   0     NaN  INTP  16.283854  2024-11-10    546.0
46  id46   93.0   대구 NaN   0    gold  ESTJ  67.886373  2024-05-23   9711.0
48  id48   18.0   대구 NaN   0     NaN  ENFP  20.129444  2024-03-25      NaN
51  id51   36.0   대구 NaN   0    gold  ISTJ  83.685380  2024-08-20   7217.0
54  id54   53.0   대구 NaN   1    gold  ENFJ  69.730313  2024-06-21   5872.0
56  id56   59.0   대구 NaN   1     vip  ESTJ  73.586397  2024-04-05  19589.0
59  id59   64.0   대구 NaN   1  silver  ESFJ  20.129444  2024-06-23   4994.0
60  id60   56.0   경기 NaN   0    gold  ESFP  52.667078  2024-11-24   6794.0
62  id62   52.0   경기 NaN   0     NaN  INTP  60.339826  2024-04-10   2100.0
65  id65   26.5   경기 NaN   0  silver  ISFP  91.297791  2024-01-10   3336.0
66  id66   87.0   경기 NaN   1    gold  ISFP  17.252986  2024-08-05   8471.0
73  id73   90.0   경기 NaN   1     NaN  ISFJ  73.586397  2024-08-12    512.0
79  id79   30.0   경기 NaN   0    gold  INTJ  80.138280  2024-08-14   8777.0
82  id82   48.0   경기 NaN   0     NaN  ENTJ  37.113739  2024-10-17      NaN
86  id86    2.0   경기 NaN   0     NaN  ESTP  29.269869  2024-02-16   2155.0
87  id87   19.0   경기 NaN   1    gold  ISFP  97.381034  2024-08-30   6516.0
90  id90   54.0   경기 NaN   0  silver  ENTP  29.269869  2024-04-03   3818.0
94  id94   84.0   경기 NaN   1  silver  ESTJ  90.496999  2024-08-16   3774.0
97  id97  100.0   경기 NaN   0    gold  INFP  67.886373  2024-03-18   6687.0

In [246]:
round(df13['age'].mean(),1)

53.6

### SECTION 14 - 중복 데이터 제거, 값 변경, 데이터 개수(p.182)

In [247]:
import numpy as np

df14 = pd.read_csv('type1_data1.csv')

In [248]:
df14 = df14.drop_duplicates()

In [249]:
# np.nan = 결측치
df14['f3'] = df14['f3'].replace(np.nan,0).replace('silver',1).replace('gold',2).replace('vip',3)

C:\Users\Administrator\AppData\Local\Temp\ipykernel_19560\3505786531.py:2: FutureWarning: Downcasting behavior in `replace` is deprecated and will be removed in a future version. To retain the old behavior, explicitly call `result.infer_objects(copy=False)`. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  df14['f3'] = df14['f3'].replace(np.nan,0).replace('silver',1).replace('gold',2).replace('vip',3)

In [250]:
int(df14['f3'].sum())

167

### SECTION 15 - 컬럼 삭제, 행 단위 합계, 필터링(p.184)

In [251]:
df15 = pd.read_csv('type1_data1.csv')

In [252]:
df15 = df15[df15.select_dtypes(exclude=object).columns]

In [253]:
df15 = df15.fillna(0)
df15

      age    f1  f2         f5   views
0     2.0   0.0   0  91.297791  6820.0
1     9.0  70.0   1  60.339826  2534.0
2    27.0  61.0   1  17.252986  7312.0
3    75.0   0.0   2  52.667078   493.0
4    24.0  85.0   2  29.269869  1338.0
..    ...   ...  ..        ...     ...
115  22.0  23.0   0   0.000000  9747.0
116  23.0  65.0   0   0.000000  5628.0
117  23.0  12.0   1   0.000000  1267.0
118  23.0  65.0   2   0.000000  6543.0
119  24.0  94.0   1   0.000000  2356.0

[120 rows x 5 columns]

In [254]:
(df15.sum(axis=1) > 3000).sum()

88

### SECTION 16 - 이상치, IQR(p.185)

In [255]:
df16 = pd.read_csv('type1_data1.csv')

In [256]:
q3 = df16['views'].quantile(.75)
q1 = df16['views'].quantile(.25)

IQR = q3 - q1
IQR

5442.5

In [257]:
line1 = q1 - IQR * 1.5
line2 = q3 + IQR * 1.5

In [258]:
cond16_1 = df16['views'] < line1
cond16_2 = df16['views'] > line2

df16 = df16[cond16_1 | cond16_2]

In [259]:
int(df16['views'].sum())

77699

### SECTION 17 - 이상치, 소수점 데이터 찾기, 표준편차(p.186)

In [260]:
df17 = pd.read_csv('type1_data1.csv')

In [261]:
r17_1 = df17['views'].std()

In [262]:
df17 = df17[df17['age'] > 0]

In [263]:
df17 = df17[df17['age'] == round(df17['age'],0)]

In [264]:
r17_2 = df17['views'].std()

In [265]:
result17 = round(r17_1)
result17

4122

### SECTION 18 - 데이터(행) 기준 평균값, 인데싱(p.187)

In [266]:
df18 = pd.read_csv('type1_data2.csv', index_col='year')

In [268]:
m18_1 = df18.loc[2001].mean()
r18_1 = sum(df18.loc[2001]> m18_1)
r18_1

100

In [270]:
m18_2 = df18.loc[2003].mean()
r18_2 = sum(df18.loc[2003]<m18_2)
r18_2

102

In [271]:
r18_1 + r18_2

202

### SECTION 19 - 결측치(뒤의 값으로 대체), 그룹합(p.189)

In [272]:
df19 = pd.read_csv('type1_data1.csv')

In [273]:
df19 = df19.fillna(method='bfill')

C:\Users\Administrator\AppData\Local\Temp\ipykernel_19560\2808910706.py:1: FutureWarning: DataFrame.fillna with 'method' is deprecated and will raise in a future version. Use obj.ffill() or obj.bfill() instead.
  df19 = df19.fillna(method='bfill')

In [276]:
df19 = df19.groupby(['city', 'f2']).sum(numeric_only=True).reset_index()
df19

   city  f2     age      f1           f5     views
0    경기   0  1192.9  1490.0  1425.236647  154066.0
1    경기   1   997.0  1016.0   935.958628   91442.0
2    경기   2   296.0   390.0   430.186433   42709.0
3    대구   0   664.0   982.0   371.184620  100421.0
4    대구   1   393.6   471.0   404.779978   49536.0
5    대구   2   185.0   321.0    79.667919   22624.0
6    부산   0   525.0   691.0   395.272907   80460.0
7    부산   1   475.7   684.0   460.657406   51624.0
8    부산   2    38.5   189.0   101.195372   17771.0
9    서울   0   241.0   480.0   484.809540   61447.0
10   서울   1   433.3   687.0   506.371383   59111.0
11   서울   2   165.3   337.0   179.328213   22405.0

In [278]:
df19 = df19.sort_values('views',ascending=False)
df19

   city  f2     age      f1           f5     views
0    경기   0  1192.9  1490.0  1425.236647  154066.0
3    대구   0   664.0   982.0   371.184620  100421.0
1    경기   1   997.0  1016.0   935.958628   91442.0
6    부산   0   525.0   691.0   395.272907   80460.0
9    서울   0   241.0   480.0   484.809540   61447.0
10   서울   1   433.3   687.0   506.371383   59111.0
7    부산   1   475.7   684.0   460.657406   51624.0
4    대구   1   393.6   471.0   404.779978   49536.0
2    경기   2   296.0   390.0   430.186433   42709.0
5    대구   2   185.0   321.0    79.667919   22624.0
11   서울   2   165.3   337.0   179.328213   22405.0
8    부산   2    38.5   189.0   101.195372   17771.0

In [277]:
df19.iloc[2,0]

'경기'